### ISSUE TITLE
Need tiff input instead of json in stac.py

### ISSUE THREAD

**Issue by cpapalaz** [stactools-packages/worldclim#5]
Template I am using uses json files as input: 

        geometry = json.loads(
        constants.get("geojson_geom").get("@value"))  # files are in tif format
    bbox = Polygon(geometry.get("coordinates")[0]).bounds

How to handle tiff files in this way? or how to manually input geometry - maybe use EPSG instead?

**Comment by cuttlefish** [comment]
`rasterio` is an option for reading in TIFF files
